cloud-media-scripts:
  image: madslundt/cloud-media-scripts
  container_name: cms
  restart: always
  volumes:
    - '/media:/local-media'
    - '/mnt/external/media:/local-decrypt'
    - '/configurations:/config'
    - '/mnt/external/plexdrive:/chunks'
    - '/logs:/log'
#  environment:
#    - PUID=1000
#    - PGID=1000
#    - TZ=Europe/Stockholm
  privileged: true
  cap_add:
    - MKNOD
    - SYS_ADMIN
  devices:
    - /dev/fuse





##############################################


#  proxy:
#    container_name: 'traefik'
#    image: traefik:1.5
#    restart: always
#    ports:
#      - '8600:80'
#    networks:
#      - proxy
#    volumes:
#      - '/var/run/docker.sock:/var/run/docker.sock'
#      - './traefik.toml:/traefik.toml'

  portainer:
    image: portainer/portainer:latest
    container_name: portainer-test
    restart: always
    ports:
      - '9900:9900'
    volumes:
      - '/mnt/data/portainer:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'

  media:
    container_name: 'media-test'
    image: madslundt/cloud-media-scripts
    restart: always
    privileged: true
    devices:
      - /dev/fuse
    cap_add:
      - CAP_MKNOD
      - CAP_SYS_ADMIN
    environment:
      ENCRYPT_MEDIA: 0
      PUID: 1000
      PGID: 1000
    volumes:
      - '/mnt/data/media/unionfs:/local-media'
      - '/mnt/data/media/local:/local-decrypt'
      - '/mnt/data/media/config:/config'
      - '/mnt/data/media/chunks:/chunks'
      - '/mnt/data/media/db:/data/db'
      - '/mnt/data/media/logs:/log'
